# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35,pep8
    - python: 3.6
      env: TOXENV=py36,pep8
    - python: 3.7
      env: TOXENV=py37,pep8
install: 
  pip install tox

script: 
  - tox -e $TOXENV

